import { createSharedQuestions, makeOption as option } from '../sharedQuestions';
import type { ServiceBranch } from '../../types/servicePlanner.types';

const branchId = 'websites' as const;

export const websitesBranch: ServiceBranch = {
  id: branchId,
  eyebrow: 'Websites',
  title: 'Build Your Presence',
  shortTitle: 'Websites',
  description:
    'Strategic websites designed to explain your value, build trust, and move visitors toward action.',
  prompt: 'What kind of website are you planning?',
  preview: {
    type: 'interactive',
    alt: 'Abstract responsive website layout preview',
    icon: 'solar:monitor-smartphone-bold-duotone',
    accent: '#B77CFF',
  },
  highlights: ['Landing pages', 'Business websites', 'E-commerce', 'Booking experiences', 'Website redesigns'],
  questions: [
    {
      id: 'website-type', branchId, stepLabel: 'Project type',
      title: 'What kind of website are you planning?',
      educationalNote: 'The website type helps estimate the number of templates, integrations, content needs, and visitor journeys involved.',
      inputType: 'single-select', required: true,
      options: [
        { ...option('landing-page', 'Landing page', 'One focused offer, campaign, event, or launch.'), complexityScore: 1, recommendationSignals: ['focused-launch'] },
        { ...option('business-website', 'Business website', 'Explain the business, build credibility, and generate action.'), complexityScore: 2, recommendationSignals: ['business-growth-website'] },
        { ...option('ecommerce', 'E-commerce', 'Sell physical or digital products, subscriptions, or services.'), complexityScore: 4, recommendationSignals: ['custom-web-experience'], nextQuestionId: 'website-stage' },
        { ...option('booking', 'Booking or reservations', 'Make scheduling central to the customer journey.'), complexityScore: 3, recommendationSignals: ['business-growth-website'] },
        { ...option('membership', 'Membership or content platform', 'Gated content, member accounts, or subscriptions.'), complexityScore: 5, recommendationSignals: ['custom-web-experience'] },
        { ...option('redesign', 'Website redesign', 'Improve an existing experience, message, or conversion path.'), complexityScore: 2 },
        option('other', 'Something else', 'Use this when the direction is still taking shape.'),
      ],
    },
    {
      id: 'website-stage', branchId, stepLabel: 'Starting point',
      title: 'Where are you starting from?',
      educationalNote: 'Replacing a site can involve migration, redirects, SEO preservation, analytics, and CMS planning in addition to the new design.',
      inputType: 'single-select', required: true,
      options: [
        option('scratch', 'Starting from scratch'),
        { ...option('replace', 'Replacing an existing website'), complexityScore: 1 },
        option('partial-improvement', 'Improving part of an existing website'),
        option('design-ready', 'Design is ready; development is needed'),
        option('development-ready', 'Development exists; design support is needed'),
        option('exploring', 'Still exploring'),
      ],
    },
    {
      id: 'website-goals', branchId, stepLabel: 'Goals',
      title: 'What should the website help your business accomplish?',
      description: 'Choose up to two priorities.', maxSelections: 2,
      educationalNote: 'A strong website is organized around the actions visitors should take—not simply around a list of pages.',
      inputType: 'multi-select', required: true,
      options: [
        option('generate-inquiries', 'Generate qualified inquiries'), option('sell-products', 'Sell products'),
        option('book', 'Book appointments or reservations'), option('explain-services', 'Explain services clearly'),
        option('build-trust', 'Build trust and credibility'), option('launch', 'Launch a new brand or product'),
        option('modernize', 'Improve an outdated experience'), option('email-list', 'Grow an email list'),
        option('promote-media', 'Promote content, music, or media'), option('campaign', 'Support an advertising campaign'),
        option('other', 'Something else'),
      ],
    },
    {
      id: 'website-size', branchId, stepLabel: 'Content size',
      title: 'How much content do you expect the website to have?',
      educationalNote: 'Page count is only one factor. Unique layouts, integrations, content volume, and functionality matter more than repeated templates.',
      inputType: 'single-select', required: true,
      options: [
        { ...option('one-page', 'One focused page'), complexityScore: 0 },
        { ...option('two-five', 'Two to five core pages'), complexityScore: 1 },
        { ...option('six-twelve', 'Six to twelve pages'), complexityScore: 2 },
        { ...option('twelve-plus', 'More than twelve pages'), complexityScore: 3 },
        { ...option('large-library', 'A large content or product library'), complexityScore: 4 },
        option('not-sure', 'Not sure yet'),
      ],
    },
    {
      id: 'website-capabilities', branchId, stepLabel: 'Capabilities',
      title: 'What does the website need to help visitors do?',
      inputType: 'multi-select', required: true,
      options: [
        option('inquiry', 'Submit an inquiry'),
        { ...option('appointment-booking', 'Schedule an appointment'), complexityScore: 2, timelineImpactWeeks: [1, 2], investmentImpact: [500, 1200] },
        { ...option('reservations', 'Make a reservation'), complexityScore: 2, timelineImpactWeeks: [1, 2], investmentImpact: [500, 1200] },
        { ...option('physical-products', 'Purchase products'), complexityScore: 3, timelineImpactWeeks: [2, 4], investmentImpact: [1200, 3000] },
        { ...option('digital-downloads', 'Purchase digital downloads'), complexityScore: 2, timelineImpactWeeks: [1, 2], investmentImpact: [800, 1800] },
        { ...option('payments', 'Pay for services'), complexityScore: 2, investmentImpact: [600, 1600] },
        { ...option('accounts', 'Create an account'), complexityScore: 3 },
        { ...option('gated-content', 'Access gated content'), complexityScore: 3 },
        { ...option('search-filter', 'Search or filter content'), complexityScore: 2 },
        option('articles', 'Read articles or resources'),
        { ...option('multilingual', 'View multiple languages'), complexityScore: 2, timelineImpactWeeks: [1, 2], investmentImpact: [600, 1500] },
        option('location', 'Find a physical location'), option('subscribe', 'Subscribe to email or SMS'),
        option('chat', 'Chat with the business'), option('other', 'Something else'),
      ],
    },
    {
      id: 'website-commerce-type', branchId, stepLabel: 'Commerce',
      title: 'What are you planning to sell?',
      educationalNote: 'Product count, fulfillment, subscriptions, and account needs can change the platform and implementation approach.',
      inputType: 'multi-select', required: true,
      visibility: { operator: 'or', conditions: [
        { questionId: 'website-type', operator: 'equals', value: 'ecommerce' },
        { questionId: 'website-goals', operator: 'includes', value: 'sell-products' },
        { questionId: 'website-capabilities', operator: 'includes', value: ['physical-products', 'digital-downloads', 'payments'] },
      ] },
      options: [option('physical-products', 'Physical products'), option('digital-products', 'Digital products'), option('services', 'Services'), option('subscriptions', 'Subscriptions'), option('tickets', 'Event tickets'), option('donations', 'Donations'), option('combination', 'A combination')],
    },
    {
      id: 'website-commerce-details', branchId, stepLabel: 'Commerce setup',
      title: 'Which store capabilities are likely to matter?',
      inputType: 'multi-select', required: false,
      visibility: { operator: 'and', conditions: [{ questionId: 'website-commerce-type', operator: 'exists' }] },
      options: [
        option('shipping', 'Shipping'), option('inventory', 'Inventory tracking'), option('discounts', 'Discount codes'),
        option('variants', 'Product variants'), option('customer-accounts', 'Customer accounts'),
        option('existing-platform', 'Existing commerce platform'), option('not-sure', 'Not sure yet'),
      ],
    },
    {
      id: 'website-booking-type', branchId, stepLabel: 'Booking',
      title: 'What kind of scheduling do you need?',
      inputType: 'single-select', required: true,
      visibility: { operator: 'or', conditions: [
        { questionId: 'website-type', operator: 'equals', value: 'booking' },
        { questionId: 'website-goals', operator: 'includes', value: 'book' },
        { questionId: 'website-capabilities', operator: 'includes', value: ['appointment-booking', 'reservations'] },
      ] },
      options: [option('appointments', 'Individual appointments'), option('classes', 'Group classes'), option('restaurant', 'Restaurant reservations'), option('services', 'Service appointments'), option('events', 'Event scheduling'), option('consultations', 'Consultation calls'), option('other', 'Other')],
    },
    {
      id: 'website-booking-platform', branchId, stepLabel: 'Booking system',
      title: 'Do you already use a scheduling system?',
      inputType: 'single-select', required: true,
      visibility: { operator: 'and', conditions: [{ questionId: 'website-booking-type', operator: 'exists' }] },
      options: ['Calendly', 'Square', 'Clover', 'Mindbody', 'Toast', 'OpenTable', 'Google Calendar', 'Another system', 'No current system'].map(label => option(label.toLowerCase().replace(/\s+/g, '-'), label)),
    },
    {
      id: 'website-content-readiness', branchId, stepLabel: 'Content',
      title: 'Who will prepare the website content?',
      description: 'Content includes written messaging, photography, products, team information, and calls to action.',
      educationalNote: 'Projects move faster when content is ready early. When it is not, we can help organize, write, or produce it.',
      inputType: 'single-select', required: true,
      options: [
        option('ready', 'Content is ready'), option('organize', 'Help organizing existing content'),
        { ...option('copywriting', 'Copywriting support'), investmentImpact: [500, 1600], timelineImpactWeeks: [1, 2], tags: ['add-on'] },
        { ...option('photo-video', 'Photography or video'), investmentImpact: [800, 2500], timelineImpactWeeks: [1, 3], tags: ['add-on'] },
        { ...option('full-support', 'Full content support'), investmentImpact: [1400, 3500], timelineImpactWeeks: [2, 4], tags: ['add-on'] },
        option('not-sure', 'Not sure'),
      ],
    },
    {
      id: 'website-brand-readiness', branchId, stepLabel: 'Brand',
      title: 'Do you already have an established visual identity?',
      inputType: 'single-select', required: true,
      options: [option('guidelines', 'Yes, with usable brand guidelines'), option('refinement', 'Yes, but it needs refinement'), option('logo-only', 'We only have a logo'), option('none', 'No established identity'), option('not-sure', 'Not sure')],
    },
    ...createSharedQuestions(branchId),
  ],
  recommendations: [
    {
      id: 'focused-launch', branchId, title: 'Focused Launch', complexity: 'foundation',
      description: 'A focused experience built around one primary offer and conversion goal.',
      bestFor: ['New business launches', 'Campaigns', 'Single services', 'Events'],
      includedDeliverables: ['Strategy alignment', 'Responsive design', 'Development', 'Conversion flow', 'SEO foundation', 'Analytics setup', 'Launch support'],
      possibleAddOns: ['Copywriting', 'Photography', 'Booking integration', 'Email setup'],
      baseTimelineWeeks: [2, 4], baseInvestmentRange: [1800, 3500],
      criteria: [
        { questionId: 'website-type', operator: 'equals', value: 'landing-page', score: 9 },
        { questionId: 'website-size', operator: 'equals', value: 'one-page', score: 7 },
      ],
    },
    {
      id: 'business-growth-website', branchId, title: 'Business Growth Website', complexity: 'growth',
      description: 'A multi-page website designed to explain your services, build trust, and turn visitors into meaningful action.',
      bestFor: ['Established service businesses', 'Restaurants', 'Healthcare', 'Professional services'],
      includedDeliverables: ['Strategy and site architecture', 'Responsive UX/UI design', 'Website development', 'CMS configuration', 'Integrations', 'SEO and analytics foundation', 'Launch support'],
      possibleAddOns: ['Copywriting', 'Content migration', 'Photography', 'Booking integration'],
      baseTimelineWeeks: [4, 7], baseInvestmentRange: [3500, 6500],
      criteria: [
        { questionId: 'website-type', operator: 'equals', value: ['business-website', 'booking', 'redesign'], score: 7 },
        { questionId: 'website-size', operator: 'equals', value: ['two-five', 'six-twelve'], score: 5 },
        { questionId: 'website-capabilities', operator: 'includes-any', value: ['appointment-booking', 'reservations', 'multilingual'], score: 4 },
      ],
    },
    {
      id: 'custom-web-experience', branchId, title: 'Custom Web Experience', complexity: 'custom',
      description: 'A tailored website platform for commerce, membership, large libraries, or advanced integrations.',
      bestFor: ['E-commerce', 'Memberships', 'Advanced booking', 'Large content libraries'],
      includedDeliverables: ['Experience strategy', 'Custom UX/UI', 'Scalable development', 'Complex integrations', 'Testing', 'Launch planning'],
      possibleAddOns: ['Content production', 'Product migration', 'Ongoing optimization'],
      baseTimelineWeeks: [7, 12], baseInvestmentRange: [7000, 14000], requiresReview: true,
      criteria: [
        { questionId: 'website-type', operator: 'equals', value: ['ecommerce', 'membership'], score: 10 },
        { questionId: 'website-size', operator: 'equals', value: ['twelve-plus', 'large-library'], score: 7 },
        { questionId: 'website-capabilities', operator: 'includes-any', value: ['accounts', 'gated-content', 'physical-products'], score: 6 },
      ],
    },
  ],
  addOns: [
    { id: 'copywriting', title: 'Copywriting', description: 'Messaging and page copy support.', timelineImpactWeeks: [1, 2], investmentRange: [500, 1600] },
    { id: 'photography', title: 'Photography or video', description: 'Original visual content production.', timelineImpactWeeks: [1, 3], investmentRange: [800, 2500] },
  ],
};
